name: deployment
on: workflow_dispatch
jobs:
  get-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: step
        run: echo "Get packages"
      - name: step 1
        run: echo "Done"
      
